# Generated by Django 3.2.23 on 2024-10-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='profession',
            new_name='country',
        ),
    ]
